// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHvQ9KA8KS5oM-gt6vVRh_lVXDos6ZNKI',
    appId: '1:25264206444:web:c27d5a95124d96ab2c1e49',
    messagingSenderId: '25264206444',
    projectId: 'flutter-test-79652',
    authDomain: 'flutter-test-79652.firebaseapp.com',
    storageBucket: 'flutter-test-79652.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF_v5pbscH3K8Hj5KqDovHA65Wr5vXul4',
    appId: '1:25264206444:android:ac649212e8cafede2c1e49',
    messagingSenderId: '25264206444',
    projectId: 'flutter-test-79652',
    storageBucket: 'flutter-test-79652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGU4hKD_xM2z_2_EpRXI6SbtpcSuMDnXw',
    appId: '1:25264206444:ios:a49825e8ffcbd7a52c1e49',
    messagingSenderId: '25264206444',
    projectId: 'flutter-test-79652',
    storageBucket: 'flutter-test-79652.appspot.com',
    iosClientId: '25264206444-vg52hunct1v5sirlk2rrpl1cpmdihfcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGU4hKD_xM2z_2_EpRXI6SbtpcSuMDnXw',
    appId: '1:25264206444:ios:a49825e8ffcbd7a52c1e49',
    messagingSenderId: '25264206444',
    projectId: 'flutter-test-79652',
    storageBucket: 'flutter-test-79652.appspot.com',
    iosClientId: '25264206444-vg52hunct1v5sirlk2rrpl1cpmdihfcq.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
